import '@sass/index.scss';
import type { Metadata } from 'next';
import { Tomorrow } from 'next/font/google';

import ReduxProvider from '@assets/Providers/ReduxProvider';


const inter = Tomorrow({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
